name: Build and deploy Node.js app to Azure Web App - Surveyreporterukapi01

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Surveyreporterukapi01
  RESOURCE_GROUP: Your-Resource-Group-Name # Add your resource group name here

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !node_modules/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Install dependencies
        run: npm install --omit=dev

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CCF81193A97443258CC9B2FAB3916586 }}

      - name: Run migrations and seed via Kudu API
        run: |
          SCM_URL="https://${{ env.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net"
          CREDENTIALS="${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CCF81193A97443258CC9B2FAB3916586 }}"

          # Install Prisma and run migrations
          curl -X POST -u "$CREDENTIALS" "$SCM_URL/api/command" \
            -H "Content-Type: application/json" \
            -d '{"command": "npm install -g prisma && npx prisma generate --schema=./prisma/schema.prisma && npx prisma migrate deploy", "dir": "site/wwwroot"}'

          # Seed the database
          curl -X POST -u "$CREDENTIALS" "$SCM_URL/api/command" \
            -H "Content-Type: application/json" \
            -d '{"command": "npm run seed", "dir": "site/wwwroot"}'
